In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

try:
    df = pd.read_csv("diamonds.csv")
except FileNotFoundError:
    sns.load_dataset("diaonds").to_csv("diamonds.csv", index=False)   # needs internet
    df = pd.read_csv("diamonds.csv")

In [4]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
df.shape

(53940, 10)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [6]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [12]:
#How many null values are there??
df.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [14]:
df.describe().round(1)

         carat    depth    table    price        x        y        z
count  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0  53940.0
mean       0.8     61.7     57.5   3932.8      5.7      5.7      3.5
std        0.5      1.4      2.2   3989.4      1.1      1.1      0.7
min        0.2     43.0     43.0    326.0      0.0      0.0      0.0
25%        0.4     61.0     56.0    950.0      4.7      4.7      2.9
50%        0.7     61.8     57.0   2401.0      5.7      5.7      3.5
75%        1.0     62.5     59.0   5324.2      6.5      6.5      4.0
max        5.0     79.0     95.0  18823.0     10.7     58.9     31.8

In [25]:
#highest carat and lowest carat
high = df["carat"].max()
low = df["carat"].min()

print("The highest carat diamond:" , high, "\n" "The lowest carat diamond :", low)

The highest carat diamond: 5.01
The lowest carat diamond : 0.2

In [26]:
print(df["cut"].value_counts())

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [6]:
df[df.duplicated()]

       carat    cut color clarity  depth  table  price     x     y     z
1005    0.79  Ideal     G     SI1   62.3   57.0   2898  5.90  5.85  3.66
1006    0.79  Ideal     G     SI1   62.3   57.0   2898  5.90  5.85  3.66
1007    0.79  Ideal     G     SI1   62.3   57.0   2898  5.90  5.85  3.66
1008    0.79  Ideal     G     SI1   62.3   57.0   2898  5.90  5.85  3.66
2025    1.52   Good     E      I1   57.3   58.0   3105  7.53  7.42  4.28
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
47969   0.52  Ideal     D     VS2   61.8   55.0   1919  5.19  5.16  3.20
49326   0.51  Ideal     F    VVS2   61.2   56.0   2093  5.17  5.19  3.17
49557   0.71   Good     F     SI2   64.1   60.0   2130  0.00  0.00  0.00
50079   0.51  Ideal     F    VVS2   61.2   56.0   2203  5.19  5.17  3.17
52861   0.50   Fair     E     VS2   79.0   73.0   2579  5.21  5.18  4.09

[146 rows x 10 columns]

In [7]:
df.drop_duplicates(inplace = True)

In [8]:
df.shape

(53794, 10)

In [ ]:
(df[["carat", "price", "x", "y", "z"]].describe())

             carat         price             x             y             z
count  53794.00000  53794.000000  53794.000000  53794.000000  53794.000000
mean       0.79778   3933.065082      5.731214      5.734653      3.538714
std        0.47339   3988.114460      1.120695      1.141209      0.705037
min        0.20000    326.000000      0.000000      0.000000      0.000000
25%        0.40000    951.000000      4.710000      4.720000      2.910000
50%        0.70000   2401.000000      5.700000      5.710000      3.530000
75%        1.04000   5326.750000      6.540000      6.540000      4.030000
max        5.01000  18823.000000     10.740000     58.900000     31.800000

In [ ]:
q1 = df["price"].quantile(0.25)
q3 = df["price"].quantile(0.75)
iqr = q3 - q1
high = q3 + 1.5 * iqr
low = q1 - 1.5 * iqr


print("q1:", q1, "q3:", q3, "IQR:", round(iqr, 1))
print("Below", round(low,1), "is an outlier")
print("Above", round(high, 1), "is an outlier")
outliers = df[(df["price"] < low) | (df["price"] > high)]
print("Total outliers:", len(outliers))
outliers.sort_values("price", ascending=False).head()

q1: 951.0 q3: 5326.75 IQR: 4375.8
Below -5612.6 is an outlier
Above 11890.4 is an outlier
Total outliers: 3523

       carat        cut color clarity  depth  table  price     x     y     z
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27747   1.51      Ideal     G      IF   61.7   55.0  18806  7.37  7.41  4.56
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01

In [26]:
print("---Max price by cut---")
print(df.groupby("cut")["price"].max().round(2))
print()
print()
print("---Max price by clarity---")
print(df.groupby("clarity")["price"].max().round(2))

---Max price by cut---
cut
Fair         18574
Good         18788
Ideal        18806
Premium      18823
Very Good    18818
Name: price, dtype: int64


---Max price by clarity---
clarity
I1      18531
IF      18806
SI1     18818
SI2     18804
VS1     18795
VS2     18823
VVS1    18777
VVS2    18768
Name: price, dtype: int64